// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plugin.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InitRequest struct {
	Config               map[string]string `protobuf:"bytes,2,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *InitRequest) Reset()         { *m = InitRequest{} }
func (m *InitRequest) String() string { return proto.CompactTextString(m) }
func (*InitRequest) ProtoMessage()    {}
func (*InitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{0}
}

func (m *InitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitRequest.Unmarshal(m, b)
}
func (m *InitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitRequest.Marshal(b, m, deterministic)
}
func (m *InitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitRequest.Merge(m, src)
}
func (m *InitRequest) XXX_Size() int {
	return xxx_messageInfo_InitRequest.Size(m)
}
func (m *InitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitRequest proto.InternalMessageInfo

func (m *InitRequest) GetConfig() map[string]string {
	if m != nil {
		return m.Config
	}
	return nil
}

type InitResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitResponse) Reset()         { *m = InitResponse{} }
func (m *InitResponse) String() string { return proto.CompactTextString(m) }
func (*InitResponse) ProtoMessage()    {}
func (*InitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{1}
}

func (m *InitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitResponse.Unmarshal(m, b)
}
func (m *InitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitResponse.Marshal(b, m, deterministic)
}
func (m *InitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitResponse.Merge(m, src)
}
func (m *InitResponse) XXX_Size() int {
	return xxx_messageInfo_InitResponse.Size(m)
}
func (m *InitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InitResponse proto.InternalMessageInfo

func (m *InitResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *InitResponse) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type SyncRequest struct {
	Engine               string                                 `protobuf:"bytes,1,opt,name=engine,proto3" json:"engine,omitempty"`
	Restore              bool                                   `protobuf:"varint,2,opt,name=restore,proto3" json:"restore,omitempty"`
	VolumeList           map[string]*SyncRequest_SyncVolRequest `protobuf:"bytes,3,rep,name=volumeList,proto3" json:"volumeList,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Params               map[string]string                      `protobuf:"bytes,4,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *SyncRequest) Reset()         { *m = SyncRequest{} }
func (m *SyncRequest) String() string { return proto.CompactTextString(m) }
func (*SyncRequest) ProtoMessage()    {}
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{2}
}

func (m *SyncRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncRequest.Unmarshal(m, b)
}
func (m *SyncRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncRequest.Marshal(b, m, deterministic)
}
func (m *SyncRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncRequest.Merge(m, src)
}
func (m *SyncRequest) XXX_Size() int {
	return xxx_messageInfo_SyncRequest.Size(m)
}
func (m *SyncRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SyncRequest proto.InternalMessageInfo

func (m *SyncRequest) GetEngine() string {
	if m != nil {
		return m.Engine
	}
	return ""
}

func (m *SyncRequest) GetRestore() bool {
	if m != nil {
		return m.Restore
	}
	return false
}

func (m *SyncRequest) GetVolumeList() map[string]*SyncRequest_SyncVolRequest {
	if m != nil {
		return m.VolumeList
	}
	return nil
}

func (m *SyncRequest) GetParams() map[string]string {
	if m != nil {
		return m.Params
	}
	return nil
}

type SyncRequest_SyncVolRequest struct {
	VolumeName           string   `protobuf:"bytes,1,opt,name=volumeName,proto3" json:"volumeName,omitempty"`
	VolumeClaim          string   `protobuf:"bytes,2,opt,name=volumeClaim,proto3" json:"volumeClaim,omitempty"`
	RemoteVolumeClaim    string   `protobuf:"bytes,3,opt,name=remoteVolumeClaim,proto3" json:"remoteVolumeClaim,omitempty"`
	LocalNS              string   `protobuf:"bytes,4,opt,name=localNS,proto3" json:"localNS,omitempty"`
	RemoteNS             string   `protobuf:"bytes,5,opt,name=remoteNS,proto3" json:"remoteNS,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncRequest_SyncVolRequest) Reset()         { *m = SyncRequest_SyncVolRequest{} }
func (m *SyncRequest_SyncVolRequest) String() string { return proto.CompactTextString(m) }
func (*SyncRequest_SyncVolRequest) ProtoMessage()    {}
func (*SyncRequest_SyncVolRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{2, 0}
}

func (m *SyncRequest_SyncVolRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncRequest_SyncVolRequest.Unmarshal(m, b)
}
func (m *SyncRequest_SyncVolRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncRequest_SyncVolRequest.Marshal(b, m, deterministic)
}
func (m *SyncRequest_SyncVolRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncRequest_SyncVolRequest.Merge(m, src)
}
func (m *SyncRequest_SyncVolRequest) XXX_Size() int {
	return xxx_messageInfo_SyncRequest_SyncVolRequest.Size(m)
}
func (m *SyncRequest_SyncVolRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncRequest_SyncVolRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SyncRequest_SyncVolRequest proto.InternalMessageInfo

func (m *SyncRequest_SyncVolRequest) GetVolumeName() string {
	if m != nil {
		return m.VolumeName
	}
	return ""
}

func (m *SyncRequest_SyncVolRequest) GetVolumeClaim() string {
	if m != nil {
		return m.VolumeClaim
	}
	return ""
}

func (m *SyncRequest_SyncVolRequest) GetRemoteVolumeClaim() string {
	if m != nil {
		return m.RemoteVolumeClaim
	}
	return ""
}

func (m *SyncRequest_SyncVolRequest) GetLocalNS() string {
	if m != nil {
		return m.LocalNS
	}
	return ""
}

func (m *SyncRequest_SyncVolRequest) GetRemoteNS() string {
	if m != nil {
		return m.RemoteNS
	}
	return ""
}

type SyncResponse struct {
	SyncID               string   `protobuf:"bytes,1,opt,name=syncID,proto3" json:"syncID,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncResponse) Reset()         { *m = SyncResponse{} }
func (m *SyncResponse) String() string { return proto.CompactTextString(m) }
func (*SyncResponse) ProtoMessage()    {}
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{3}
}

func (m *SyncResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncResponse.Unmarshal(m, b)
}
func (m *SyncResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncResponse.Marshal(b, m, deterministic)
}
func (m *SyncResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncResponse.Merge(m, src)
}
func (m *SyncResponse) XXX_Size() int {
	return xxx_messageInfo_SyncResponse.Size(m)
}
func (m *SyncResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SyncResponse proto.InternalMessageInfo

func (m *SyncResponse) GetSyncID() string {
	if m != nil {
		return m.SyncID
	}
	return ""
}

func (m *SyncResponse) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type SyncStatusRequest struct {
	SyncID               string   `protobuf:"bytes,1,opt,name=syncID,proto3" json:"syncID,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncStatusRequest) Reset()         { *m = SyncStatusRequest{} }
func (m *SyncStatusRequest) String() string { return proto.CompactTextString(m) }
func (*SyncStatusRequest) ProtoMessage()    {}
func (*SyncStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{4}
}

func (m *SyncStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncStatusRequest.Unmarshal(m, b)
}
func (m *SyncStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncStatusRequest.Marshal(b, m, deterministic)
}
func (m *SyncStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncStatusRequest.Merge(m, src)
}
func (m *SyncStatusRequest) XXX_Size() int {
	return xxx_messageInfo_SyncStatusRequest.Size(m)
}
func (m *SyncStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SyncStatusRequest proto.InternalMessageInfo

func (m *SyncStatusRequest) GetSyncID() string {
	if m != nil {
		return m.SyncID
	}
	return ""
}

func (m *SyncStatusRequest) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type SyncStatusResponse struct {
	Status               int32             `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Reason               string            `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Params               map[string]string `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SyncStatusResponse) Reset()         { *m = SyncStatusResponse{} }
func (m *SyncStatusResponse) String() string { return proto.CompactTextString(m) }
func (*SyncStatusResponse) ProtoMessage()    {}
func (*SyncStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{5}
}

func (m *SyncStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncStatusResponse.Unmarshal(m, b)
}
func (m *SyncStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncStatusResponse.Marshal(b, m, deterministic)
}
func (m *SyncStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncStatusResponse.Merge(m, src)
}
func (m *SyncStatusResponse) XXX_Size() int {
	return xxx_messageInfo_SyncStatusResponse.Size(m)
}
func (m *SyncStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SyncStatusResponse proto.InternalMessageInfo

func (m *SyncStatusResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *SyncStatusResponse) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *SyncStatusResponse) GetParams() map[string]string {
	if m != nil {
		return m.Params
	}
	return nil
}

func init() {
	proto.RegisterType((*InitRequest)(nil), "proto.InitRequest")
	proto.RegisterMapType((map[string]string)(nil), "proto.InitRequest.ConfigEntry")
	proto.RegisterType((*InitResponse)(nil), "proto.InitResponse")
	proto.RegisterType((*SyncRequest)(nil), "proto.SyncRequest")
	proto.RegisterMapType((map[string]string)(nil), "proto.SyncRequest.ParamsEntry")
	proto.RegisterMapType((map[string]*SyncRequest_SyncVolRequest)(nil), "proto.SyncRequest.VolumeListEntry")
	proto.RegisterType((*SyncRequest_SyncVolRequest)(nil), "proto.SyncRequest.SyncVolRequest")
	proto.RegisterType((*SyncResponse)(nil), "proto.SyncResponse")
	proto.RegisterType((*SyncStatusRequest)(nil), "proto.SyncStatusRequest")
	proto.RegisterType((*SyncStatusResponse)(nil), "proto.SyncStatusResponse")
	proto.RegisterMapType((map[string]string)(nil), "proto.SyncStatusResponse.ParamsEntry")
}

func init() { proto.RegisterFile("plugin.proto", fileDescriptor_22a625af4bc1cc87) }

var fileDescriptor_22a625af4bc1cc87 = []byte{
	// 480 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4d, 0x8b, 0x13, 0x41,
	0x10, 0x65, 0xf2, 0x65, 0xac, 0x59, 0xd4, 0x2d, 0x65, 0x69, 0xe7, 0xb0, 0xc4, 0x80, 0xb0, 0x07,
	0x89, 0x90, 0x05, 0xbf, 0x40, 0x41, 0xb3, 0x1e, 0x16, 0x24, 0xc8, 0x04, 0x72, 0xb6, 0x0d, 0x6d,
	0x18, 0x9c, 0xe9, 0x8e, 0xd3, 0x3d, 0x0b, 0xb9, 0xf9, 0x17, 0xfc, 0x31, 0x7a, 0xf4, 0xb7, 0x49,
	0x7f, 0xcc, 0x58, 0xb3, 0x3b, 0x7b, 0xd8, 0x3d, 0x25, 0xaf, 0xfa, 0x55, 0x75, 0xbf, 0x57, 0x2f,
	0x81, 0x83, 0x5d, 0x5e, 0x6d, 0x33, 0x39, 0xdb, 0x95, 0xca, 0x28, 0x1c, 0xba, 0x8f, 0xe9, 0xcf,
	0x08, 0xe2, 0x73, 0x99, 0x99, 0x54, 0xfc, 0xa8, 0x84, 0x36, 0xf8, 0x02, 0x46, 0x1b, 0x25, 0xbf,
	0x65, 0x5b, 0xd6, 0x9b, 0xf4, 0x4f, 0xe2, 0xf9, 0xb1, 0xa7, 0xcf, 0x08, 0x67, 0xb6, 0x70, 0x84,
	0x8f, 0xd2, 0x94, 0xfb, 0x34, 0xb0, 0x93, 0xd7, 0x10, 0x93, 0x32, 0x3e, 0x80, 0xfe, 0x77, 0xb1,
	0x67, 0xd1, 0x24, 0x3a, 0xb9, 0x9b, 0xda, 0xaf, 0xf8, 0x08, 0x86, 0x17, 0x3c, 0xaf, 0x04, 0xeb,
	0xb9, 0x9a, 0x07, 0x6f, 0x7a, 0xaf, 0xa2, 0xe9, 0x3b, 0x38, 0xf0, 0xd3, 0xf5, 0x4e, 0x49, 0x2d,
	0xf0, 0x08, 0x46, 0xda, 0x70, 0x53, 0x69, 0xd7, 0x3e, 0x4c, 0x03, 0xb2, 0xf5, 0x52, 0x70, 0xad,
	0x64, 0x18, 0x11, 0xd0, 0xf4, 0xd7, 0x00, 0xe2, 0xd5, 0x5e, 0x6e, 0x6a, 0x09, 0x47, 0x30, 0x12,
	0x72, 0x9b, 0x49, 0x11, 0xae, 0x0f, 0x08, 0x19, 0xdc, 0x29, 0x85, 0x36, 0xaa, 0xf4, 0x6f, 0x18,
	0xa7, 0x35, 0xc4, 0x0f, 0x00, 0x17, 0x2a, 0xaf, 0x0a, 0xf1, 0x29, 0xd3, 0x86, 0xf5, 0x9d, 0xf0,
	0x69, 0x10, 0x4e, 0x26, 0xcf, 0xd6, 0x0d, 0xc9, 0x8b, 0x27, 0x5d, 0xd6, 0xb8, 0x1d, 0x2f, 0x79,
	0xa1, 0xd9, 0xa0, 0x65, 0x1c, 0xed, 0xff, 0xec, 0x08, 0xc1, 0x38, 0xcf, 0x4e, 0xfe, 0x44, 0x70,
	0xcf, 0x72, 0xd6, 0x2a, 0xaf, 0x05, 0x1c, 0xd7, 0xcf, 0x59, 0xf2, 0xa2, 0x16, 0x41, 0x2a, 0x38,
	0x81, 0xd8, 0xa3, 0x45, 0xce, 0xb3, 0x22, 0xb8, 0x41, 0x4b, 0xf8, 0x0c, 0x0e, 0x4b, 0x51, 0x28,
	0x23, 0xd6, 0x84, 0xd7, 0x77, 0xbc, 0xab, 0x07, 0xd6, 0x98, 0x5c, 0x6d, 0x78, 0xbe, 0x5c, 0xb1,
	0x81, 0xe3, 0xd4, 0x10, 0x13, 0x18, 0x7b, 0xfa, 0x72, 0xc5, 0x86, 0xee, 0xa8, 0xc1, 0xc9, 0x17,
	0xb8, 0x7f, 0xc9, 0x8f, 0x8e, 0xad, 0xbf, 0xa4, 0x5b, 0x8f, 0xe7, 0x4f, 0x3a, 0x4c, 0x69, 0x8b,
	0x27, 0xc1, 0xb0, 0x99, 0x22, 0x8e, 0xdd, 0x34, 0x53, 0xfe, 0x0e, 0x92, 0xa9, 0xbd, 0xdc, 0x9c,
	0x9f, 0xd5, 0x99, 0xf0, 0xe8, 0xda, 0x4c, 0x2d, 0xe0, 0xd0, 0xf6, 0xaf, 0x5c, 0xf2, 0x48, 0xb0,
	0x6e, 0x34, 0xe4, 0x6f, 0x04, 0x48, 0xa7, 0xdc, 0x2e, 0xdf, 0xf8, 0xb6, 0x49, 0x96, 0x4f, 0xe6,
	0x53, 0x62, 0x62, 0x7b, 0x74, 0x67, 0xc0, 0x6e, 0xef, 0xe2, 0xfc, 0x77, 0x04, 0x70, 0xc6, 0x0d,
	0xb7, 0x37, 0x89, 0x12, 0x9f, 0xc3, 0xc0, 0xfe, 0x50, 0x11, 0xaf, 0xfe, 0x27, 0x24, 0x0f, 0x5b,
	0xb5, 0xa0, 0xf4, 0x14, 0xc6, 0xb6, 0xd5, 0x8e, 0x68, 0x9a, 0xc8, 0xea, 0x9b, 0xa6, 0xd6, 0xaa,
	0xde, 0x03, 0xfc, 0x57, 0x86, 0xac, 0x43, 0xac, 0x6f, 0x7e, 0x7c, 0xad, 0x0d, 0x5f, 0x47, 0xee,
	0xe4, 0xf4, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6e, 0xe5, 0x90, 0x1b, 0xf2, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DataSyncerClient is the client API for DataSyncer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DataSyncerClient interface {
	Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error)
	SyncData(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error)
	SyncStatus(ctx context.Context, in *SyncStatusRequest, opts ...grpc.CallOption) (*SyncStatusResponse, error)
}

type dataSyncerClient struct {
	cc *grpc.ClientConn
}

func NewDataSyncerClient(cc *grpc.ClientConn) DataSyncerClient {
	return &dataSyncerClient{cc}
}

func (c *dataSyncerClient) Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error) {
	out := new(InitResponse)
	err := c.cc.Invoke(ctx, "/proto.DataSyncer/Init", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSyncerClient) SyncData(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error) {
	out := new(SyncResponse)
	err := c.cc.Invoke(ctx, "/proto.DataSyncer/SyncData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSyncerClient) SyncStatus(ctx context.Context, in *SyncStatusRequest, opts ...grpc.CallOption) (*SyncStatusResponse, error) {
	out := new(SyncStatusResponse)
	err := c.cc.Invoke(ctx, "/proto.DataSyncer/SyncStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataSyncerServer is the server API for DataSyncer service.
type DataSyncerServer interface {
	Init(context.Context, *InitRequest) (*InitResponse, error)
	SyncData(context.Context, *SyncRequest) (*SyncResponse, error)
	SyncStatus(context.Context, *SyncStatusRequest) (*SyncStatusResponse, error)
}

// UnimplementedDataSyncerServer can be embedded to have forward compatible implementations.
type UnimplementedDataSyncerServer struct {
}

func (*UnimplementedDataSyncerServer) Init(ctx context.Context, req *InitRequest) (*InitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Init not implemented")
}
func (*UnimplementedDataSyncerServer) SyncData(ctx context.Context, req *SyncRequest) (*SyncResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncData not implemented")
}
func (*UnimplementedDataSyncerServer) SyncStatus(ctx context.Context, req *SyncStatusRequest) (*SyncStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncStatus not implemented")
}

func RegisterDataSyncerServer(s *grpc.Server, srv DataSyncerServer) {
	s.RegisterService(&_DataSyncer_serviceDesc, srv)
}

func _DataSyncer_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSyncerServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DataSyncer/Init",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSyncerServer).Init(ctx, req.(*InitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSyncer_SyncData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSyncerServer).SyncData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DataSyncer/SyncData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSyncerServer).SyncData(ctx, req.(*SyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSyncer_SyncStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSyncerServer).SyncStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DataSyncer/SyncStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSyncerServer).SyncStatus(ctx, req.(*SyncStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DataSyncer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DataSyncer",
	HandlerType: (*DataSyncerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Init",
			Handler:    _DataSyncer_Init_Handler,
		},
		{
			MethodName: "SyncData",
			Handler:    _DataSyncer_SyncData_Handler,
		},
		{
			MethodName: "SyncStatus",
			Handler:    _DataSyncer_SyncStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}
