// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/plugin/proto/plugin.proto

package proto

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InitRequest struct {
	Params               map[string]string `protobuf:"bytes,1,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *InitRequest) Reset()         { *m = InitRequest{} }
func (m *InitRequest) String() string { return proto.CompactTextString(m) }
func (*InitRequest) ProtoMessage()    {}
func (*InitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1205a7d920adc07, []int{0}
}

func (m *InitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitRequest.Unmarshal(m, b)
}
func (m *InitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitRequest.Marshal(b, m, deterministic)
}
func (m *InitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitRequest.Merge(m, src)
}
func (m *InitRequest) XXX_Size() int {
	return xxx_messageInfo_InitRequest.Size(m)
}
func (m *InitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitRequest proto.InternalMessageInfo

func (m *InitRequest) GetParams() map[string]string {
	if m != nil {
		return m.Params
	}
	return nil
}

type InitResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitResponse) Reset()         { *m = InitResponse{} }
func (m *InitResponse) String() string { return proto.CompactTextString(m) }
func (*InitResponse) ProtoMessage()    {}
func (*InitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1205a7d920adc07, []int{1}
}

func (m *InitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitResponse.Unmarshal(m, b)
}
func (m *InitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitResponse.Marshal(b, m, deterministic)
}
func (m *InitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitResponse.Merge(m, src)
}
func (m *InitResponse) XXX_Size() int {
	return xxx_messageInfo_InitResponse.Size(m)
}
func (m *InitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InitResponse proto.InternalMessageInfo

type SyncRequest struct {
	Params               map[string]string `protobuf:"bytes,1,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SyncRequest) Reset()         { *m = SyncRequest{} }
func (m *SyncRequest) String() string { return proto.CompactTextString(m) }
func (*SyncRequest) ProtoMessage()    {}
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1205a7d920adc07, []int{2}
}

func (m *SyncRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncRequest.Unmarshal(m, b)
}
func (m *SyncRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncRequest.Marshal(b, m, deterministic)
}
func (m *SyncRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncRequest.Merge(m, src)
}
func (m *SyncRequest) XXX_Size() int {
	return xxx_messageInfo_SyncRequest.Size(m)
}
func (m *SyncRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SyncRequest proto.InternalMessageInfo

func (m *SyncRequest) GetParams() map[string]string {
	if m != nil {
		return m.Params
	}
	return nil
}

type SyncResponse struct {
	SyncID               string   `protobuf:"bytes,1,opt,name=syncID,proto3" json:"syncID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncResponse) Reset()         { *m = SyncResponse{} }
func (m *SyncResponse) String() string { return proto.CompactTextString(m) }
func (*SyncResponse) ProtoMessage()    {}
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1205a7d920adc07, []int{3}
}

func (m *SyncResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncResponse.Unmarshal(m, b)
}
func (m *SyncResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncResponse.Marshal(b, m, deterministic)
}
func (m *SyncResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncResponse.Merge(m, src)
}
func (m *SyncResponse) XXX_Size() int {
	return xxx_messageInfo_SyncResponse.Size(m)
}
func (m *SyncResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SyncResponse proto.InternalMessageInfo

func (m *SyncResponse) GetSyncID() string {
	if m != nil {
		return m.SyncID
	}
	return ""
}

type SyncStatusRequest struct {
	Params               map[string]string `protobuf:"bytes,1,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SyncStatusRequest) Reset()         { *m = SyncStatusRequest{} }
func (m *SyncStatusRequest) String() string { return proto.CompactTextString(m) }
func (*SyncStatusRequest) ProtoMessage()    {}
func (*SyncStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1205a7d920adc07, []int{4}
}

func (m *SyncStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncStatusRequest.Unmarshal(m, b)
}
func (m *SyncStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncStatusRequest.Marshal(b, m, deterministic)
}
func (m *SyncStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncStatusRequest.Merge(m, src)
}
func (m *SyncStatusRequest) XXX_Size() int {
	return xxx_messageInfo_SyncStatusRequest.Size(m)
}
func (m *SyncStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SyncStatusRequest proto.InternalMessageInfo

func (m *SyncStatusRequest) GetParams() map[string]string {
	if m != nil {
		return m.Params
	}
	return nil
}

type SyncStatusResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncStatusResponse) Reset()         { *m = SyncStatusResponse{} }
func (m *SyncStatusResponse) String() string { return proto.CompactTextString(m) }
func (*SyncStatusResponse) ProtoMessage()    {}
func (*SyncStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1205a7d920adc07, []int{5}
}

func (m *SyncStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncStatusResponse.Unmarshal(m, b)
}
func (m *SyncStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncStatusResponse.Marshal(b, m, deterministic)
}
func (m *SyncStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncStatusResponse.Merge(m, src)
}
func (m *SyncStatusResponse) XXX_Size() int {
	return xxx_messageInfo_SyncStatusResponse.Size(m)
}
func (m *SyncStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SyncStatusResponse proto.InternalMessageInfo

func (m *SyncStatusResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func init() {
	proto.RegisterType((*InitRequest)(nil), "proto.InitRequest")
	proto.RegisterMapType((map[string]string)(nil), "proto.InitRequest.ParamsEntry")
	proto.RegisterType((*InitResponse)(nil), "proto.InitResponse")
	proto.RegisterType((*SyncRequest)(nil), "proto.SyncRequest")
	proto.RegisterMapType((map[string]string)(nil), "proto.SyncRequest.ParamsEntry")
	proto.RegisterType((*SyncResponse)(nil), "proto.SyncResponse")
	proto.RegisterType((*SyncStatusRequest)(nil), "proto.SyncStatusRequest")
	proto.RegisterMapType((map[string]string)(nil), "proto.SyncStatusRequest.ParamsEntry")
	proto.RegisterType((*SyncStatusResponse)(nil), "proto.SyncStatusResponse")
}

func init() { proto.RegisterFile("pkg/plugin/proto/plugin.proto", fileDescriptor_c1205a7d920adc07) }

var fileDescriptor_c1205a7d920adc07 = []byte{
	// 298 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2d, 0xc8, 0x4e, 0xd7,
	0x2f, 0xc8, 0x29, 0x4d, 0xcf, 0xcc, 0xd3, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x87, 0x72, 0xf4, 0xc0,
	0x1c, 0x21, 0x56, 0x30, 0xa5, 0xd4, 0xc0, 0xc8, 0xc5, 0xed, 0x99, 0x97, 0x59, 0x12, 0x94, 0x5a,
	0x58, 0x9a, 0x5a, 0x5c, 0x22, 0x64, 0xc6, 0xc5, 0x56, 0x90, 0x58, 0x94, 0x98, 0x5b, 0x2c, 0xc1,
	0xa8, 0xc0, 0xac, 0xc1, 0x6d, 0x24, 0x07, 0x51, 0xae, 0x87, 0xa4, 0x46, 0x2f, 0x00, 0xac, 0xc0,
	0x35, 0xaf, 0xa4, 0xa8, 0x32, 0x08, 0xaa, 0x5a, 0xca, 0x92, 0x8b, 0x1b, 0x49, 0x58, 0x48, 0x80,
	0x8b, 0x39, 0x3b, 0xb5, 0x52, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0xc4, 0x14, 0x12, 0xe1,
	0x62, 0x2d, 0x4b, 0xcc, 0x29, 0x4d, 0x95, 0x60, 0x02, 0x8b, 0x41, 0x38, 0x56, 0x4c, 0x16, 0x8c,
	0x4a, 0x7c, 0x5c, 0x3c, 0x10, 0xd3, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0xc1, 0x4e, 0x0a, 0xae,
	0xcc, 0x4b, 0x26, 0xe4, 0x24, 0x24, 0x35, 0xd4, 0x76, 0x92, 0x1a, 0x17, 0x0f, 0xc4, 0x74, 0x88,
	0x93, 0x84, 0xc4, 0xb8, 0xd8, 0x8a, 0x2b, 0xf3, 0x92, 0x3d, 0x5d, 0xa0, 0xda, 0xa1, 0x3c, 0xa5,
	0x1e, 0x46, 0x2e, 0x41, 0x90, 0xc2, 0xe0, 0x92, 0xc4, 0x92, 0xd2, 0x62, 0x98, 0x83, 0x6d, 0xd0,
	0x1c, 0xac, 0x82, 0xe4, 0x60, 0x14, 0x95, 0xd4, 0x76, 0xb6, 0x0e, 0x97, 0x10, 0xb2, 0x1d, 0x48,
	0x8e, 0x07, 0x8b, 0x80, 0x0d, 0x61, 0x0d, 0x82, 0xf2, 0x8c, 0xb6, 0x32, 0x72, 0x71, 0xb9, 0x24,
	0x96, 0x24, 0x82, 0xb4, 0xa4, 0x16, 0x09, 0xe9, 0x73, 0xb1, 0x80, 0xa2, 0x41, 0x48, 0x08, 0x33,
	0xc6, 0xa5, 0x84, 0x51, 0xc4, 0xa0, 0xe6, 0x1a, 0x73, 0x71, 0x80, 0xb4, 0x82, 0x8c, 0x80, 0x6b,
	0x42, 0x8a, 0x13, 0xb8, 0x26, 0x94, 0x90, 0x74, 0xe4, 0xe2, 0x42, 0x38, 0x51, 0x48, 0x02, 0x57,
	0xc8, 0x48, 0x49, 0x62, 0x91, 0x81, 0x18, 0x91, 0xc4, 0x06, 0x96, 0x31, 0x06, 0x04, 0x00, 0x00,
	0xff, 0xff, 0x56, 0x18, 0x07, 0xec, 0xe1, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DataSyncerClient is the client API for DataSyncer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DataSyncerClient interface {
	Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error)
	SyncData(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error)
	SyncStatus(ctx context.Context, in *SyncStatusRequest, opts ...grpc.CallOption) (*SyncStatusResponse, error)
}

type dataSyncerClient struct {
	cc grpc.ClientConnInterface
}

func NewDataSyncerClient(cc grpc.ClientConnInterface) DataSyncerClient {
	return &dataSyncerClient{cc}
}

func (c *dataSyncerClient) Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error) {
	out := new(InitResponse)
	err := c.cc.Invoke(ctx, "/proto.DataSyncer/Init", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSyncerClient) SyncData(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error) {
	out := new(SyncResponse)
	err := c.cc.Invoke(ctx, "/proto.DataSyncer/SyncData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSyncerClient) SyncStatus(ctx context.Context, in *SyncStatusRequest, opts ...grpc.CallOption) (*SyncStatusResponse, error) {
	out := new(SyncStatusResponse)
	err := c.cc.Invoke(ctx, "/proto.DataSyncer/SyncStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataSyncerServer is the server API for DataSyncer service.
type DataSyncerServer interface {
	Init(context.Context, *InitRequest) (*InitResponse, error)
	SyncData(context.Context, *SyncRequest) (*SyncResponse, error)
	SyncStatus(context.Context, *SyncStatusRequest) (*SyncStatusResponse, error)
}

// UnimplementedDataSyncerServer can be embedded to have forward compatible implementations.
type UnimplementedDataSyncerServer struct {
}

func (*UnimplementedDataSyncerServer) Init(ctx context.Context, req *InitRequest) (*InitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Init not implemented")
}
func (*UnimplementedDataSyncerServer) SyncData(ctx context.Context, req *SyncRequest) (*SyncResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncData not implemented")
}
func (*UnimplementedDataSyncerServer) SyncStatus(ctx context.Context, req *SyncStatusRequest) (*SyncStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncStatus not implemented")
}

func RegisterDataSyncerServer(s *grpc.Server, srv DataSyncerServer) {
	s.RegisterService(&_DataSyncer_serviceDesc, srv)
}

func _DataSyncer_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSyncerServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DataSyncer/Init",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSyncerServer).Init(ctx, req.(*InitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSyncer_SyncData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSyncerServer).SyncData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DataSyncer/SyncData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSyncerServer).SyncData(ctx, req.(*SyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSyncer_SyncStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSyncerServer).SyncStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DataSyncer/SyncStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSyncerServer).SyncStatus(ctx, req.(*SyncStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DataSyncer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DataSyncer",
	HandlerType: (*DataSyncerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Init",
			Handler:    _DataSyncer_Init_Handler,
		},
		{
			MethodName: "SyncData",
			Handler:    _DataSyncer_SyncData_Handler,
		},
		{
			MethodName: "SyncStatus",
			Handler:    _DataSyncer_SyncStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/plugin/proto/plugin.proto",
}
