apiVersion: v1
kind: Service
metadata:
  name: moveengine
  namespace: kubemove
  labels:
    name: move-engine
spec:
  ports:
  - port: 9000
    name: moveengine
  type: ClusterIP
  selector:
    name: move-engine
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: move-engine
  namespace: kubemove
spec:
  replicas: 1
  selector:
    matchLabels:
      name: move-engine
  template:
    metadata:
      labels:
        name: move-engine
    spec:
      serviceAccountName: kubemove
      containers:
      - name: move-engine
        # Replace this with the built image name
        image: ${REGISTRY}/move-engine:ci
        imagePullPolicy: IfNotPresent
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "kubemove"
